artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/shubhamgogri/dump_data/raw/main/hotel_reservation.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts\data_ingestion\dynamic_reservations_feat.csv
  STATUS_FILE: artifacts/data_validation/status.txt


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts\data_ingestion\dynamic_reservations_feat.csv
  target: pickup_3
  cutoff_date: 01-01-2024